### ISSUE TITLE
Display the Hybrid heat pump as one entity in front-end

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1368]
RIght now the Hybrid heat pump is split up into two pieces. We would like to display it as one technology. The thing is, I know how this would work in the front-end. However, I have no idea what the damages will be during the calculation (I guess, it would be significant).

Current situation

Front-end -> Calculator:
````
HHP (e) -> HHP (e)
HHP (g) -> HHP (g)
````

Front-end -> Calculator
````
HHP -> HHP (e)
    -> HHP (g)
````

----

Things that need to be edited:

- [x] Import needs to change to a single HHP
- [x] Split the HHP when calculating

**Comment by antw** [comment]
This would definitely be nice. Perhaps it could be handled similarly to base loads, where a single front-end technology is split into two separate parts before being handed off to the calculation?

The complicating factor in this case is that the two parts use different carriers. This means that [technology_component_behavior](https://github.com/quintel/etmoses/blob/b4838ac1df4256f4d9dda58fc3227672e651a9be/db/static/technologies/base_load.yml#L9-L11) would likely need to become something more detailed:

```yaml
behavior: hhp

components:
  electric:
    behavior: hhp_electricity
    carrier: electricity
    position_relative_to_buffer: buffering
  gas:
    behavior: hhp_gas
    carrier: gas
    position_relative_to_buffer: boosting

# etc...
```

... where each "component" would inherit the attributes of the main technology.

**Comment by grdw** [comment]
I'm having multiple questions stating from the content that's in the separate parts of the hybrid heat pumps:

Summarized content of the Hybrids that spawn questions (I filterd out all the obvious things):

````yml
---
carrier: hybrid
color: "#57A753"
behavior: buffer
visible: false
````

Content of the electricity part:
````yaml
---
behavior: hhp_electricity
carrier: electricity
color: "#9ED2A1"
defaults:
  capacity: 4.9
  initial_investment: 3235.0
  om_costs_per_year: 96.7
  performance_coefficient: 4.5
  position_relative_to_buffer: buffering
  technical_lifetime: 15

expandable: false
export_to: households_space_heater_hybrid_heatpump_air_water_electricity_share
````

Content of the gas part:
````yaml
---
behavior: hhp_gas
carrier: gas
color: "#80C37D"
defaults:
  capacity: 22.0
  initial_investment: 1500.0
  om_costs_per_year: 156.2
  performance_coefficient: 1.067
  position_relative_to_buffer: boosting
  technical_lifetime: 15
````

A few things I see missing are the `color`, `export_to`. Could we also add those to the `components` or wouldn't that make any sense?

Also the defaults, what do we need to do with those, if we're going to merge them both? @ChaelKruip or are the defaults based of the things that we extract from the main hybrid heat pump from ETEngine?

**Comment by antw** [comment]
> What are we going to do with the `color` attributes, and the `export_to` for the electricity part. Could we also add those to the `components` or wouldn't that make any sense?

I suppose we could. I understand your concern, especially with the `defaults`; costs and lifetime would be shared between both components, but the capacity, performance coefficient, and "position relative to buffer" are different for each component. This does feel a bit inelegant.

I wish I had a better idea to offer. 😧

**Comment by grdw** [comment]
Couldn't we keep the information concerning defaults in both components and associate the components from the hybrid heat pump. 

````yml
---
carrier: hybrid
color: "#57A753"
behavior: hhp

components:
  - electric
  - gas
````

In `Technology`:

````ruby
class Technology
  ...
  def components
    attributes[:components].map do |part|
      Technology.find_by_key("#{ key }_#{ part }")
    end
  end
  ...
end
````

And in `Network::Technologies`

````
def self.from_installed(installed, profile, options = {})
    # expand the hybrid heat pump in two technologies?
end
````

This would take some changes to the calculator I guess but I don't know how hard that'd be. The only issue I see here is that you can't really simply edit the costs of a single component of the Hybrid heat pump or the capacity for that matter.
