### ISSUE TITLE
NICE TO HAVE: distribution of households should take capacity of topology into account

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#336]
Currently, the important topologies (e.g., `default`) have a `capacity` and `units` attribute. This would allow ETMoses to be able to distribute households and technologies according to the available capacity of the end-points. For example a scenario with 100 households could be coupled to a topology with two -end-points. Currently, ETMoses would divide the HHs 50/50 over the end-points. The suggested change would make it possible to edit the topology to look like:

```
 - name: 'MV-LV Trafo'
    children:
    - name: Household group 1
      capacity: 17.25
      units: 33
    - name: Household group 2
      capacity: 17.25
      units: 66
```
and ETMoses to assign the households in the ratio described above.
