### ISSUE TITLE
Warning message for incompatibility of topology and market model should be more verbose

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#430]
Right now it just tells me that some stakeholders are not compatible:
![cursor_and_etmoses](https://cloud.githubusercontent.com/assets/1303760/10041379/337e66b0-61e4-11e5-81e1-d5c8ef17f5b4.png)

It would really help if the user gets a list of those that are in the Market Model but not in the topology (and vice versa).

**Comment by ChaelKruip** [comment]
For example, I'm using the default topology:
```
---
name: HV Network
stakeholder: producer
children:
- name: HV-MV Trafo
  capacity: 16000
  technical_lifetime: 30
  investment_cost: 150000
  stakeholder: system operator
  children:
  - name: 'MV-LV Trafo #1'
    capacity: 2000
    technical_lifetime: 30
    investment_cost: 50000
    stakeholder: system operator
    children:
    - name: Households 1
      capacity: 17.25
      units: 33
      stakeholder: customer
  - name: 'MV-LV Trafo #2'
    capacity: 2000
    technical_lifetime: 30
    investment_cost: 50000
    stakeholder: system operator
    children:
    - name: Households 2
      capacity: 17.25
      units: 33
      stakeholder: customer
  - name: 'MV-LV Trafo #3'
    capacity: 2000
    technical_lifetime: 30
    investment_cost: 50000
    stakeholder: system operator
    children:
    - name: Households 3
      capacity: 17.25
      units: 33
      stakeholder: cooperation
```
which includes, `producer`, `customer`, `system operator` and `cooperation`.

My [market model](http://beta.moses.et-model.com/market_models/63) includes all of these stakeholders except the `system operator`:
<img width="1371" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/10122150/53e72676-650e-11e5-811c-945665629346.png">

but still I get the warning for incompatibility!
