### ISSUE TITLE
Aggregation of load goes wrong

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#643]
I'm working on a case with high penetration of E-cars but cannot see congestion. If you only just multiply number of E-cars with their capacity it results in load much higher than what I see in the loadcurve. 826 times 3.7 kW + 413 times 22 kW ~ 12000 kW

http://beta.moses.et-model.com/testing_grounds/375
![image](https://cloud.githubusercontent.com/assets/7781037/11531345/6b9fe75e-98fc-11e5-8952-ff254ba00876.png)

![image](https://cloud.githubusercontent.com/assets/7781037/11531333/58dc017a-98fc-11e5-8a37-6d1ebbe52a62.png)

**Comment by ChaelKruip** [comment]
Re-assigning to @grdw

**Comment by grdw** [comment]
> E-cars but cannot see congestion

The congestion is not seen because the node in question doesn't have a capacity. 

````yaml
.....
      - name: LS cable veld B
         .....
          children:
          - name: KVB Veld B
            stakeholder: customer AC1a
          ....
....
````

This way the front end doesn't know when a certain end-point is congested.
