### ISSUE TITLE
Investment costs are defined as for all the units or per unit?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#659]
And: is this intentional?

**Comment by ChaelKruip** [comment]
Per unit. This is intentional :smile:

**Comment by dennisschoenmakers** [comment]
> Per unit.

So, if I update the topology of a LES from:

```yaml
---
name: HV Network
stakeholder: producer
children:
- name: HV-MV Trafo
  capacity: 16000
  technical_lifetime: 30
  investment_cost: 150000
  units: 1
  stakeholder: system operator
  children:
  [...]
```

To:

```yaml
---
name: HV Network
stakeholder: producer
children:
- name: HV-MV Trafo
  capacity: 16000
  technical_lifetime: 30
  investment_cost: 150000
  units: 10000 #<----------- A LOT MORE!
  stakeholder: system operator
  children:
  [...]
```

I would expect the yearly costs of the System Operator to be higher.

but in the interface it remains 10.000 EUR. :unamused: 

LES that I used: http://beta.moses.et-model.com/testing_grounds/341
