### ISSUE TITLE
No network cost are allocated to system operator

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#952]
Although there are operational_cost in the topology for the system operator I cannot find these cost in the business case.

test 2016-05-03 on production server

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by grdw** [comment]
The nodes that are related to the system operator stakeholder are excluded from the calculation due to missing properties. In order for the topology costs to be taken into account for a certain node the following attributes have to be present: 

- `investment_cost` attribute
- `stakeholder` attribute (which is present 👍 ) 
- lifetime (being either a `technical_lifetime` or `economic_lifetime` attribute)

Also I see that the term `operational_cost` is used. The correct syntax here would be `yearly_o_and_m_costs`. Unless these terms are semantically two separate things? 

You can see which attributes to use [here](https://github.com/quintel/etmoses/wiki/Topologies#attributes).

**Comment by JeroenvdLogt** [comment]
Nope unfortenately it still doesn't work. In this case all investment cost are 'versdiconteerd' in the operational cost.

---
name: HV Network
stakeholder: producer
children:
- name: MV/LV transformator
  stakeholder: system operator
  capacity: 417
  yearly_o_and_m_costs: 1534
  children:
  - name: Afgaand LS veld
    units: 4
    stakeholder: system operator
    capacity: 260
    yearly_o_and_m_costs: 3228
    children:
    - name: Aansluiting huishoudens
      units: 60
      stakeholder: customer AC1a
      capacity: 1440
      economic_lifetime: 60
    - name: Aansluiting MKB
      units: 8
      stakeholder: customer AC2a
      capacity: 200
      economic_lifetime: 60

**Comment by grdw** [comment]
To clearify my comment in an example:

````yaml
---
name: HV Network
stakeholder: producer
children:
- name: MV/LV transformator
  stakeholder: system operator
  capacity: 417
  yearly_o_and_m_costs: 1534
  investment_cost: ???  <--
  economic_lifetime: ??? <--
  children:
  - name: Afgaand LS veld
    units: 4
    stakeholder: system operator
    capacity: 260
    yearly_o_and_m_costs: 3228
    investment_cost: ???  <--
    economic_lifetime: ??? <--
    children:
    - name: Aansluiting huishoudens
      units: 60
      stakeholder: customer AC1a
      capacity: 1440
      economic_lifetime: 60
    - name: Aansluiting MKB
      units: 8
      stakeholder: customer AC2a
      capacity: 200
      economic_lifetime: 60
````

It needs the `investment_cost` and `ecnomic_lifetime` attributes for those nodes in order for the `yearly_o_and_m_costs` to be taken into account. We could change this though, considering the fact  that you might not know the values to these attributes. 

What you could do in the mean time is specify the `investment_cost` as 0 and the `economic_lifetime` as some number larger than or 1. This way the `investment_cost` will be 0 and the `yearly_o_and_m_costs` will be simply added to that value.

````yaml
---
name: HV Network
stakeholder: producer
children:
- name: MV/LV transformator
  stakeholder: system operator
  capacity: 417
  yearly_o_and_m_costs: 1534
  investment_cost: 0
  economic_lifetime: 1
  children:
  - name: Afgaand LS veld
    units: 4
    stakeholder: system operator
    capacity: 260
    yearly_o_and_m_costs: 3228
    investment_cost: 0
    economic_lifetime: 1
    children:
    - name: Aansluiting huishoudens
      units: 60
      stakeholder: customer AC1a
      capacity: 1440
      economic_lifetime: 60
    - name: Aansluiting MKB
      units: 8
      stakeholder: customer AC2a
      capacity: 200
      economic_lifetime: 60
````

So this should work.
