### ISSUE TITLE
Add defaults Hash in technologies yml files

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#957]
Perhaps instead of default_capacity, default_volume, and default_demand, we might have a defaults hash instead?

````yaml
defaults:
  capacity: 4.0
  volume: 10.0
````
